require('dotenv').config();
const express=require('express'),session=require('express-session'),axios=require('axios'),crypto=require('crypto'),path=require('path'),fs=require('fs'),Razorpay=require('razorpay');
app.set('trust proxy', 1);
const app=express(),ROOT=__dirname,PORT=process.env.PORT||3000;
const rawBody=express.raw({type:'application/json'});app.post('/webhooks/razorpay',rawBody,webhook);app.use(express.json({limit:'1mb'}));app.use(session({secret:process.env.SESSIONKEY||'dev-change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*3600000}}));app.use(express.static(path.join(ROOT,'public')));
const c={repo:process.env.GITHUB_REPO,branch:process.env.GITHUB_BRANCH||'main',token:process.env.GITHUB_TOKEN,products:process.env.PRODUCTS_FILE||'data/products.json',orders:process.env.ORDERS_FILE||'data/orders.json',coupons:process.env.COUPONS_FILE||'data/coupons.json',events:process.env.EVENTS_FILE||'data/events.json'};
const gh=()=>({Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28',Accept:'application/vnd.github+json'});const local=f=>path.join(ROOT,f);
async function read(f){if(c.repo&&c.token){const u=`https://api.github.com/repos/${c.repo}/contents/${f}?ref=${c.branch}`;const x=await axios.get(u,{headers:gh()});return {data:JSON.parse(Buffer.from(x.data.content,'base64')),sha:x.data.sha}}return {data:JSON.parse(fs.readFileSync(local(f),'utf8')),sha:null}}
async function write(f,data,msg){if(c.repo&&c.token){for(let n=0;n<3;n++)try{const x=await read(f);await axios.put(`https://api.github.com/repos/${c.repo}/contents/${f}`,{message:msg,content:Buffer.from(JSON.stringify(data,null,2)).toString('base64'),sha:x.sha,branch:c.branch},{headers:gh()});return}catch(e){if(e.response?.status!==409||n===2)throw e}}else fs.writeFileSync(local(f),JSON.stringify(data,null,2))}
async function event(req,type,data={}){try{const x=await read(c.events);x.data.push({id:crypto.randomUUID(),type,at:new Date().toISOString(),session:req.sessionID,...data});await write(c.events,x.data,`Analytics ${type}`)}catch(e){console.error('Analytics:',e.message)}}
const auth=(q,s,n)=>q.session.isAuthenticated?n():s.status(401).json({message:'Admin session required'});const safe=x=>String(x||'').trim();const isExpired=d=>Boolean(d)&&new Date(d+'T23:59:59.999').getTime()<Date.now();
app.get('/api/products',async(q,s)=>s.json((await read(c.products)).data));app.get('/api/products/:slug',async(q,s)=>{const a=(await read(c.products)).data,p=a.find(x=>x.slug===q.params.slug);p?s.json({...p,related:a.filter(x=>x.id!==p.id&&(x.category===p.category)).slice(0,4)}):s.status(404).json({message:'Product not found'})});
app.post('/api/track',async(q,s)=>{const allowed=['product_view','wishlist_add','wishlist_remove','cart_add','cart_remove','checkout_started','checkout_abandoned','payment_failed'];if(!allowed.includes(q.body.type))return s.status(400).end();await event(q,q.body.type,{productId:safe(q.body.productId),name:safe(q.body.name),mobile:safe(q.body.mobile),orderId:safe(q.body.orderId),reason:safe(q.body.reason)});s.json({ok:true})});
app.post('/api/coupon',async(q,s)=>{const code=safe(q.body.code).toUpperCase(),sub=+q.body.subtotal||0,x=(await read(c.coupons)).data.find(z=>z.active&&z.code===code);if(!x||isExpired(x.expiresAt)||sub<x.minOrder)return s.status(400).json({message:'Invalid coupon or minimum order not met'});let discount=x.type==='percent'?Math.floor(sub*x.value/100):x.value;discount=Math.min(discount,sub);s.json({code,discount,total:sub-discount})});
app.post('/admin/admin-login',(q,s)=>{const now=Date.now();if(q.session.lockUntil>now)return s.status(429).json({message:'Too many attempts. Please try again after 5 minutes.'});const p=safe(q.body.password);if(!/^\d{4,}$/.test(p))return s.status(400).json({message:'Password must contain only numbers and be longer than 3 characters.'});if(p===String(process.env.ADMIN_PASSWORD||'12345')){q.session.isAuthenticated=true;q.session.loginAttempts=0;return s.json({message:'Admin login successful.'})}q.session.loginAttempts=(q.session.loginAttempts||0)+1;if(q.session.loginAttempts>=3){q.session.lockUntil=now+300000;return s.status(429).json({message:'Too many attempts. Please try again after 5 minutes.'})}s.status(401).json({message:'Invalid password, Please try again.'})});
app.post('/admin/logout',(q,s)=>q.session.destroy(()=>s.json({ok:true})));app.get('/admin/getOrders',auth,async(q,s)=>s.json((await read(c.orders)).data));app.get('/admin/analytics',auth,async(q,s)=>{const [o,e,p]=await Promise.all([read(c.orders),read(c.events),read(c.products)]),orders=o.data,events=e.data,paid=orders.reduce((a,x)=>a+(+x.amount||0),0),count=t=>events.filter(x=>x.type===t).length;s.json({orders:orders.length,revenue:paid,delivered:orders.filter(x=>x.current_status==='Delivered').length,pending:orders.filter(x=>!['Delivered','Rejected','Returned'].includes(x.current_status)).length,failed:count('payment_failed'),abandoned:count('checkout_abandoned'),wishlists:count('wishlist_add'),cartAdds:count('cart_add'),events:events.slice(-250).reverse(),topProducts:Object.values(orders.flatMap(x=>x.items||[]).reduce((a,x)=>{a[x.product_id]??={name:x.name,qty:0};a[x.product_id].qty+=+x.quantity||1;return a},{})).sort((a,b)=>b.qty-a.qty).slice(0,5),products:p.data.length})});
app.post('/admin/updateOrderStatus',auth,async(q,s)=>{let{orderId,status,trackingDetails}=q.body;const allowed=['Order Placed','Order Confirmed','Packed','Shipped','Out for Delivery','Delivered','Rejected','Returned'];if(!allowed.includes(status))return s.status(400).json({message:'Invalid status'});const x=await read(c.orders),i=x.data.findIndex(o=>o.order_id===orderId);if(i<0)return s.status(404).json({message:'Order not found'});if(trackingDetails&&x.data[i].current_status==='Order Placed')status='Shipped';x.data[i].current_status=status;x.data[i].tracking_details=trackingDetails||'';x.data[i].tracking_history=(x.data[i].tracking_history||[]).concat({status,at:new Date().toISOString(),details:trackingDetails||''});await write(c.orders,x.data,`Update status ${orderId}`);s.json({message:'Status updated',status})});
app.get('/admin/getLocationByPincode',auth,async(q,s)=>{try{const x=await axios.get(`https://api.postalpincode.in/pincode/${encodeURIComponent(q.query.pincode||'')}`),p=x.data?.[0]?.PostOffice?.[0];p?s.json({success:true,location:p.Name,state:p.State,district:p.District,country:'India'}):s.status(404).json({success:false})}catch(e){s.status(502).json({success:false})}});
app.post('/admin/products',auth,async(q,s)=>{const x=await read(c.products),p=q.body;if(!p.id||!p.slug||!p.name)return s.status(400).json({message:'ID, slug and name required'});const i=x.data.findIndex(z=>z.id===p.id);const clean={...p,price:+p.price,oldPrice:+p.oldPrice,stock:+p.stock,gallery:p.gallery||[p.image],features:p.features||[],specs:p.specs||{}};i<0?x.data.push(clean):x.data[i]=clean;await write(c.products,x.data,`Save product ${p.id}`);s.json({message:'Product saved'})});app.delete('/admin/products/:id',auth,async(q,s)=>{const x=await read(c.products);x.data=x.data.filter(z=>z.id!==q.params.id);await write(c.products,x.data,`Delete product ${q.params.id}`);s.json({message:'Product deleted'})});
app.post('/admin/coupons',auth,async(q,s)=>{const x=await read(c.coupons),v={code:safe(q.body.code).toUpperCase(),type:q.body.type,value:+q.body.value,minOrder:+q.body.minOrder,expiresAt:safe(q.body.expiresAt),active:q.body.active!==false},i=x.data.findIndex(z=>z.code===v.code);i<0?x.data.push(v):x.data[i]=v;await write(c.coupons,x.data,`Save coupon ${v.code}`);s.json({message:'Coupon saved'})});app.get('/admin/coupons',auth,async(q,s)=>s.json((await read(c.coupons)).data));
app.post('/my-orders',async(q,s)=>{const m=safe(q.body.mobileNumber),a=(await read(c.orders)).data.filter(o=>o.mobile===m).sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));a.length?s.json({message:'Order details found',orders:a}):s.status(404).json({message:'No order found for this mobile number'})});
app.post('/my-orders/submit-feedback',async(q,s)=>{const{orderId,shipping,packaging,product,feedback}=q.body;if([shipping,packaging,product].some(v=>+v<1||+v>5))return s.status(400).json({message:'Please select all ratings'});const x=await read(c.orders),i=x.data.findIndex(o=>o.order_id===orderId);if(i<0)return s.status(404).json({message:'Order not found'});const old=x.data[i].feedback_timestamp;if(old&&old!=='NA'&&Date.now()-new Date(old)>7*86400000)return s.status(403).json({message:'Feedback editing window has expired'});const overall=Math.ceil((+shipping+ +packaging+ +product)/3);Object.assign(x.data[i],{feedback:`${shipping}${packaging}${product}${overall}`,review_text:feedback||'',feedback_timestamp:new Date().toISOString()});await write(c.orders,x.data,`Feedback ${orderId}`);s.json({message:'Thank you for your feedback, Warranty claimed!'})});app.get('/review/getOrders',async(q,s)=>s.json((await read(c.orders)).data.filter(o=>o.feedback&&o.feedback!=='NA')));
const rp=process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;
app.post('/createOrder',async(q,s)=>{try{if(!rp)return s.status(503).json({message:'Payment gateway is not configured'});const inputCustomer=q.body.customer||{},name=safe(inputCustomer.name),mobile=safe(inputCustomer.mobile),address=safe(inputCustomer.address),pincode=safe(inputCustomer.pincode);if(!/^[A-Za-z\u0900-\u097F .'-]{2,60}$/.test(name)||!/^[6-9]\d{9}$/.test(mobile)||address.length<10||!/^\d{6}$/.test(pincode))return s.status(400).json({message:'Please enter valid customer details'});const ps=(await read(c.products)).data,items=(q.body.items||[]).map(v=>{const p=ps.find(x=>x.id===v.productId);if(!p)throw Error('Invalid product');return {...p,quantity:Math.max(1,Math.min(10,+v.quantity||1))}}),subtotal=items.reduce((a,x)=>a+x.price*x.quantity,0),coupon=safe(q.body.coupon).toUpperCase();let discount=0;if(coupon){const cp=(await read(c.coupons)).data.find(z=>z.active&&z.code===coupon);if(!cp||isExpired(cp.expiresAt)||subtotal<cp.minOrder)throw Error('Coupon is invalid or minimum order is not met');discount=cp.type==='percent'?Math.floor(subtotal*cp.value/100):cp.value;discount=Math.min(discount,subtotal)}const total=Math.max(1,subtotal-discount),customer={name,mobile,address,pincode};const order=await rp.orders.create({amount:Math.round(total*100),currency:'INR',receipt:`rcpt_${Date.now()}`,notes:{mobile:safe(customer.mobile)}});q.session.checkout={items,subtotal,discount,total,customer,coupon,razorpayOrderId:order.id};await event(q,'checkout_started',{name:safe(customer.name),mobile:safe(customer.mobile),orderId:order.id});s.json({...order,key:process.env.RAZORPAY_KEY_ID})}catch(e){s.status(400).json({message:e.message})}});
app.post('/verifyPayment',async(q,s)=>{try{const{payment_id,order_id,signature}=q.body,x=q.session.checkout;if(!x||x.razorpayOrderId!==order_id)return s.status(400).json({success:false,message:'Checkout mismatch'});const exp=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${order_id}|${payment_id}`).digest('hex');if(exp!==signature)return s.status(400).json({success:false});const now=new Date().toISOString(),record={...x.customer,order_id,payment_id,items:x.items.map(v=>({product_id:v.id,name:v.name,price:v.price,quantity:v.quantity})),subtotal:x.subtotal,discount:x.discount,coupon:x.coupon,amount:x.total,date:now.slice(0,10),time:now.slice(11,19),created_at:now,current_status:'Order Placed',feedback:'NA',feedback_timestamp:'NA',review_text:'NA',tracking_details:'NA',tracking_history:[{status:'Order Placed',at:now}]};const o=await read(c.orders);o.data.push(record);await write(c.orders,o.data,`New order ${order_id}`);q.session.checkout=null;s.json({success:true,order:record})}catch(e){s.status(500).json({success:false,message:e.message})}});
async function webhook(q,s){try{const sig=q.headers['x-razorpay-signature'],secret=process.env.RAZORPAY_WEBHOOK_SECRET;if(!secret)return s.status(503).end();const exp=crypto.createHmac('sha256',secret).update(q.body).digest('hex');if(sig!==exp)return s.status(400).end();const body=JSON.parse(q.body.toString());if(body.event==='payment.failed'){const p=body.payload.payment.entity,x=await read(c.events);x.data.push({id:crypto.randomUUID(),type:'payment_failed',at:new Date().toISOString(),orderId:p.order_id,mobile:p.contact||'',reason:p.error_description||p.error_reason||'Payment failed'});await write(c.events,x.data,'Razorpay payment failed')}s.json({ok:true})}catch(e){s.status(500).end()}}
app.get('/admin',(q,s)=>q.session.isAuthenticated?s.sendFile(path.join(ROOT,'public/admin.html')):s.redirect('/'));for(const [u,f] of [['/','index.html'],['/product/:slug','product.html'],['/cart','cart.html'],['/my-orders','orders.html'],['/review','review.html'],['/FAQs','faq.html'],['/policies','policies.html']])app.get(u,(q,s)=>s.sendFile(path.join(ROOT,'public',f)));app.get('/health',(q,s)=>s.json({ok:true,githubStorage:Boolean(c.repo&&c.token)}));app.listen(PORT,()=>console.log(`AutoClickerMouse running on http://localhost:${PORT}`));
